name: clashmi
description: clashmi

publish_to: none 
version: 1.0.0+24
environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: 1.0.8
  dash_flags: 0.1.1
  package_info_plus: 8.3.0
  class_to_string: 1.0.0
  ffi: 2.1.3
  url_launcher: 6.3.1
  flutter_inappwebview:
    #path: ../../KaringX/flutter_inappwebview/flutter_inappwebview
    git: 
      url: https://github.com/KaringX/flutter_inappwebview.git
      ref: 3a5ead04885537489f3226a04cd0481a90183bbe #v6.2.0-beta.3
      path: flutter_inappwebview
  #flutter_inappwebview: 6.2.0-beta.2
  web_socket_channel: 2.4.0 #flutter_test
  path_provider: 2.1.5
  flutter_secure_storage: 9.2.4
  protocol_handler: 0.1.6 #0.2.0 cause windows jam when exit
  json_annotation: ^4.9.0
  re_editor: ^0.6.0
  re_highlight: ^0.0.3
  launch_at_startup: 0.2.2 #pc only 0.2.2 - 0.3.1 StartupApproved cause reg exceptions
  provider: 6.1.2
  zxing2: 0.2.3
  qr_code_scanner_plus: 2.0.10+1
  screen_capturer: 0.2.3 #pc only
  contextmenu: 3.0.0
  image: 4.5.4
  uuid: 4.4.0 #flutter_test 
  slang: 4.6.0
  slang_flutter: 4.6.0
  watcher: 1.1.1
  string_validator: 1.1.0
  punycode_converter: 0.2.1
  scrollview_observer: 1.26.0
  after_layout: 1.2.0
  #animated_toggle_switch: 0.8.0
  flutter_install_referrer: 2.0.2
  windows_single_instance: 1.0.1 #windows only
  flutter_plugin_android_lifecycle: 2.0.24 #file_picker image_picker
  file_picker: 9.2.1
  image_picker: 1.1.2
  tray_manager: 0.4.0 # pc only
  hotkey_manager: 0.2.3  # pc only
  #accessibility_tools: 2.2.2
  android_package_manager: 0.7.1
  logger: 2.5.0
  tuple: 2.0.2
  crypto: 3.0.6
  cryptography: 2.7.0
  cryptography_flutter: 2.3.2
  open_dir: 0.0.2+1 #pc only
  path: 1.9.0 #flutter_test
  characters: 1.3.0 #flutter_test
  win32_registry: 1.1.5 #flutter_test
  share_plus: 10.1.4 
  open_file: 3.5.10 
  app_installer: ^1.3.1
  app_settings: 5.2.0
  webdav_client: 1.2.2
  mime: 1.0.4
  http: 1.2.2
  http_parser: 4.0.2
  icloud_storage: 2.2.0 #https://github.com/lollipopkit/flutter_server_box/blob/d94b2a7805891da3e652a9a65cc0c774a2ec6db4/lib/core/utils/sync/icloud.dart#L32
  archive: 4.0.4
  google_mobile_ads: 5.3.1
  move_to_background: #1.0.2
    #path: ../move_to_background/
    git:
      url: https://github.com/KaringX/move_to_background.git
      ref: 9720fa00946af134caf04b05702230d4329f857f
  country: # 4.1.9
    #path: ../country/country/
    git:
      url: https://github.com/KaringX/country.git
      ref: e744de90f18911a595a486413b535b486fc92219
      path: country
  window_manager: #0.3.7 #pc only
    #path: ../window_manager/packages/
    git:
      url: https://github.com/KaringX/window_manager.git
      ref: f0a01b386c45c4a3513811720e2b5fc765ca45f2
      path: packages/window_manager
  libclash_vpn_service:
    path: ../libclash-vpn-service/
 
    #git:
      #url: https://github.com/KaringX/libclash-vpn-service.git
      #ref: master

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0 #dart run build_runner build --delete-conflicting-outputs


flutter:
  uses-material-design: true
  assets:
    - assets/zashboard/
    - assets/zashboard/assets/
    - assets/txts/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/datas/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Emoji # from hiddify
      fonts:
        - asset: assets/fonts/Emoji.ttf


#https://www.appicon.co/
flutter_launcher_icons: #flutter pub run flutter_launcher_icons
  android: ic_launcher
  ios: true
  image_path: logo-round.png 
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path_android: logo-round.png
  image_path_ios: logo.png
  remove_alpha_ios: true
  windows:
    generate: false 
    image_path: logo-round.png
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: logo-round-macos.png #macos https://github.com/Yidadaa/ChatGPT-Next-Web/issues/156  1024 -> 854 -> 1024
 